image:
  repository: p3terx/aria2-pro
  tag: latest
  pullPolicy: IfNotPresent
ariangImage:
  repository: p3terx/ariang
  tag: latest
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 6880
        protocol: http
  rpc:
    enabled: true
    ports:
      rpc:
        enabled: true
        port: 6800
        targetPort: 6800
        protocol: http
  listen:
    enabled: true
    ports:
      listen:
        enabled: true
        port: 6888
        protocol: tcp
workload:
  main:
    type: Deployment
    podSpec:
      containers:
        main:
          enabled: true
          primary: true
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            RPC_PORT: "{{ .Values.service.rpc.ports.rpc.port }}"
            LISTEN_PORT: "{{ .Values.service.listen.ports.listen.port }}"
            DISK_CACHE: 64M
            IPV6_MODE: false
            UPDATE_TRACKERS: false
            CUSTOM_TRACKER_URL: "https://trackerslist.com/all_aria2.txt"
            RPC_SECRET: "ChangemeNow"
  ariang:
    enabled: true
    type: Deployment
    strategy: RollingUpdate
    replicas: 1
    podSpec:
      containers:
        ariang:
          enabled: true
          primary: true
          imageSelector: ariangImage
          probes:
            liveness:
              type: tcp
              path: /
              port: 6880
            readiness:
              type: tcp
              path: /
              port: 6880
            startup:
              type: tcp
              path: /
              port: 6880
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: false
ariang:
  enabled: true
aria2pro:
  enabled: true
  path: "/jsonrpc"
