image:
  repository: p3terx/ariang-pro
  tag: latest
  pullPolicy: IfNotPresent
ariangImage:
  repository: p3terx/ariang
  tag: latest
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 6800
        protocol: http
  ariang:
    enabled: true
    ports:
      ariang:
        enabled: true
        port: 6880
        protocol: http
  listen:
    enabled: true
    ports:
      listen:
        enabled: true
        port: 6888
        protocol: tcp
workload:
  main:
    type: Deployment
    podSpec:
      containers:
        main:
          enabled: true
          primary: true
          ports:
            - containerPort: "{{ .Values.service.main.ports.main.port }}"
              name: main
          env:
            RPC_PORT: "{{ .Values.service.main.ports.main.port }}"
            LISTEN_PORT: "{{ .Values.service.listen.ports.listen.port }}"
            DISK_CACHE: 64M
            IPV6_MODE: false
            UPDATE_TRACKERS: true
            CUSTOM_TRACKER_URL: "https://trackerslist.com/all_aria2.txt"
            RPC_SECRET: "ChangemeNow"
          probes:
            liveness:
              type: tcp
              path: /jsonrpc
              port: "{{ .Values.service.main.ports.main.port }}"
            readiness:
              type: tcp
              path: /jsonrpc
              port: "{{ .Values.service.main.ports.main.port }}"
            startup:
              type: tcp
              path: /jsonrpc
              port: "{{ .Values.service.main.ports.main.port }}"
        # aria2rpc:
        #   name: aria2rpc
        #   image: "{{ .Values.aria2proImage.repository }}:{{ .Values.aria2proImage.tag }}"
        #   ports:
        #     - containerPort: "{{ .Values.service.rpc.ports.rpc.port }}"
        #       name: main 
        #   env:
        #     RPC_PORT: "{{ .Values.service.rpc.ports.rpc.port }}"
        #     LISTEN_PORT: "{{ .Values.service.listen.ports.listen.port }}"
        #     DISK_CACHE: 64M
        #     IPV6_MODE: false
        #     UPDATE_TRACKERS: true
        #     CUSTOM_TRACKER_URL: "https://trackerslist.com/all_aria2.txt"
        #     RPC_SECRET: "ChangemeNow"
        #   probes:
        #     liveness:
        #       type: http
        #       path: /jsonrpc
        #       port: "{{ .Values.service.rpc.ports.rpc.port }}"
        #     readiness:
        #       type: http
        #       path: /jsonrpc
        #       port: "{{ .Values.service.rpc.ports.rpc.port }}"
        #     startup:
        #       type: http
        #       path: /jsonrpc
        #       port: "{{ .Values.service.rpc.ports.rpc.port }}"    

additionalContainers:
  ariang:
    name: ariang
    image: {{ .Values.ariangImage.repository }}:{{ .Values.ariangImage.tag }}
    imagePullPolicy: '{{ .Values.ariangImage.pullPolicy }}'
    securityContext:
      runAsUser: {{ .Values.securityContext.container.runAsUser }}
      runAsGroup: {{ .Values.securityContext.runAsGroup }}
      readOnlyRootFilesystem: {{ .Values.securityContext.container.readOnlyRootFilesystem }}
      runAsNonRoot: {{ .Values.securityContext.container.runAsNonRoot }}
    ports:
      - containerPort: {{ .Values.service.ariang.ports.ariang.port }}
        name: main
    probes:
      liveness:
        type: tcp
        path: /
        port: "{{ .Values.service.ariang.ports.ariang.port }}"
      readiness:
        type: tcp
        path: /
        port: "{{ .Values.service.ariang.ports.ariang.port }}"
      startup:
        type: tcp
        path: /
        port: "{{ .Values.service.ariang.ports.ariang.port }}"
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: false
ariang:
  enabled: true
aria2rpc:
  enabled: true
  path: "/jsonrpc"
